repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pre-commit
    rev: v2.16.0
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/antisvin/owl_midi
    rev: f4d2dcd19786721af7eb9c752d28aca87e5072a2
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
